### ISSUE TITLE
Forbid selling NFTs of the project as part as the CoC

### ISSUE THREAD

**Issue by jdubois** [ContributorCovenant/contributor_covenant#1042]
## Thank you

First of all, thank you so much for creating this project. This has helped tremendously the https://github.com/jhipster community.

## What's happening with NFTs currently

There are several companies selling NFTs of Git commit hashes. For example https://gitnft.quine.sh - of course this doesn't benefit the project at all, and is done without anyone's consent or even knowledge on the project.

## Why this is bad

I find this breaks the CoC in 3 main ways:

- This system is a Ponzi scheme that targets minorities. As you might know, several studies (see https://finance.yahoo.com/news/black-latino-lgbtq-investors-see-100412051.html ) show that minorities are more attracted to NFTs. For example, that study show that 23% of Black Americans own crypto, and only 11% of White Americans. Using our project and community to target minorities and scam them is against our goals.
- The CoC specifically says "Other conduct which could reasonably be considered inappropriate in a professional setting".  Let me translate this NFT situation in a professional setting: imagine I tell my colleagues that I'm starting some side-business of speculating on their Git commit hashes. How would they react? Imagine I tell one of them that I did a NFT on their latest commit, and I'm going to sell it for a profit to someone else. I can include some real-life colleagues in this thread if you have any doubt on their reaction.
- "Focusing on what is best not just for us as individuals, but for the overall community": there is documented evidence that crypto mining is an ecological nightmare (see https://www.nytimes.com/interactive/2021/09/03/climate/bitcoin-carbon-footprint-electricity.html ). I'm pretty sure that everyone in my community would be against this idea of destroying the planet for money - and even worse, so that other people (who aren't part of the project), make money.

## My proposal

I would like to discuss how we could had a section in the CoC to make it clear that selling NFTs of our Git commit hashes (or any other NFTs based on our Open Source work) is disallowed.

**Comment by coderbyheart** [comment]
I think it will be challenging to legally enforce that, because these NFT sh*theads are not redistributing the software (and thus creating a copy the falls under the copyright license), but are basically putting an identifying string composed of repo name and commit hash on the blockchain and sell the token that claims to own that identifier.

**Comment by kiview** [comment]
I think it is a very heavy bikeshedding topic and probably hard to formulate what actually needs to be forbidden. Also, most of those NFTs aren't even clear for themselves what owning them actually entails. I don't know in which way copyright extends on hashes or URLs. 

Edit:
I just checked https://opensea.io/assets/matic/0xe7ea2e2be12c257d376400cb231d8ee51e972bd6/112378023207334916646627084922865532126660405318784463929118418006790614554412 and the token itself contains a copy of the commit message. I would assume that the commit message itself could fall under copyright, so this might be in violation (IANAL).

**Comment by jdubois** [comment]
- The copyright extends to the hash and URL, as the author also creates them. They are part of the project.
- Taking a picture of it doesn't change anything. It's the same thing if you take a picture of Mickey Mouse, Disney still owns the copyright of Mickey Mouse. That's the same reason why you can't copy a Disney film and sell it as your own.

**Comment by jdubois** [comment]
My comment above isn't good. We shouldn't talk about copyright or legal infringement here, that's not the point.
The point is to prevent some bad practices from a community perspective, which might or might not be legal.

**Comment by kiview** [comment]
I think if this is phrased in non-legal language, that's much better.

**Comment by dradetsky** [comment]
I very much disagree with the inclusion of this as part of the CC, as I think it is out of scope. Perhaps it would make more sense within the context of https://github.com/EthicalSource/hippocratic-license-3, although I haven't really thought that through.

I'm not totally sure whether GitNFT and others are working with projects (who may or may have a relevant CoC), or just stamping random git metadata on the blockchain and hoping suckers will buy it, or some combination depending on the circumstances. But I don't think it particularly matters. The main issue is that if you add provisions to the CC which target or appear to target certain technologies or industries, you either make the adoption of CC impossible for those projects, or at least communicate to the leaders of those projects that the CC and perhaps CoCs in general are not for them.

I assume that those who disapprove of NFTs and related nonsense still agree that members of NFT project communities ought to be protected from harassment or discrimination. I suppose it's possible that some people believe that NFTs and NFT projects are evil, and thus members of those projects deserve to be discriminated against for _(rolls dice)_ color or body size, or that at least this discrimination may help to prevent NFT projects from being too effective. But if people do think this (and I'm not judging, just a little surprised), they should at least make it explicit so there's no confusion.

**Comment by jdubois** [comment]
As this has been opened for more than one year, let's close this as this is not moving forward.
I understand this didn't make a consensus, even if I'm sad as I wanted to protect our users and contributors, mainly in non privileged communities (again, they are the ones most targeted by Ponzi schemes).
