### ISSUE TITLE
Why is the list of adopters not being updated?

### ISSUE THREAD

**Issue by mbtools** [ContributorCovenant/contributor_covenant#1060]
There are a lot of PRs in the queue to add adopters to the list. What's the hold up?

**Comment by Danialahwaz** [comment]
#

**Comment by mbtools** [comment]
I did a review of all open PRs asking for updates. I check the URLs and presence of CODE_OF_CONDUCT. 

The following can be approved (either v1.4 or v2.0 of CoC):

#606, #608, #638, #656, #670, #714, #722, #747, #748, #761, #762, #840, #852, #957, #961

The following are no good (suggest closing):

#630, #670, #722, #730, #753

The following ask for removal and should be approved:

#766

**Comment by mbtools** [comment]
If you like I can combine these requests into a new PR and add them in the correct sort order:

Backlight deb packages, https://github.com/gorlapraveen/blacklight-deb-packages
BioSigKit, https://github.com/hooman650/BioSigKit
brightness_bashshell_script, https://github.com/gorlapraveen/brightness_bashshell_script
Create Rome App, https://github.com/romeland/create-rome-app
Deviser Platform, https://github.com/deviserplatform/deviserplatform
Drachenhorn, https://github.com/Drachenhorn-Team/Drachenhorn
fanKounter, https://github.com/HZKnight/fanKounter
Firefox B2B Communication for Internet access, https://github.com/gorlapraveen/firefox_b2b_comm_radio_addon
Firefox Browser to B2B Communication, https://github.com/gorlapraveen/firefox_b2b_comm_radio_addon
irhamdzuhri.com, https://github.com/irhamdz/irhamdzuhri.com
Java Builders Generator, https://github.com/khabali/java-builders-generator
jPOS, https://github.com/jpos
Linkedin skills, https://github.com/shweteekta/100-Days-of-ML-Code-/blob/master/Scrapping%20of%20linkedin%20Skills.py
Open WebRTC Toolkit, https://github.com/open-webrtc-toolkit
prance (Resolving Swagger/OpenAPI 2.0 Parser), https://github.com/jfinkhaeuser/prance
Robopager, https://github.com/equinoxfitness/robopager
ROOT-Sim, https://github.com/HPDCS/ROOT-Sim/
Rowy, https://github.com/rowyio/rowy
Skeptycal.com, https://github.com/buefy/buefy
Soosyze CMS, https://soosyze.com/charte-code-conduite-contributeurs
SOSC/VTU-Lab-Material, https://github.com/so-sc/VTU-Lab-Material/
Stack.io, https://github.com/germanstack
Weaviate, https://github.com/semi-technologies/weaviate

**Comment by alessandropellegrini** [comment]
#747 has been updated. The CoC file is in the docs subfolder, which is supported by GitHub.

**Comment by mbtools** [comment]
Thanks! I adjusted the list above

**Comment by alessandropellegrini** [comment]
Thanks a lot for the quick feedback!

**Comment by CoralineAda** [comment]
@mbtools We would welcome a consolidated PR-- thanks so much for your diligence here!

**Comment by mbtools** [comment]
Here you go 😃
