### ISSUE TITLE
Project maintainers vs Community leaders

### ISSUE THREAD

**Issue by tfiers** [ContributorCovenant/contributor_covenant#1073]
This wording changed from 1.x to 2.x.
The 2.0 changelog  entry mentions about it:
> - Emphasizes 'community' over 'project' scope, effectively merging the Community Covenant into the Contributor Covenant
> - Moves enforcement responsibilities from project maintainers to community leaders

I was interested in reading more.
I've been searching this repo's gh, google, and the website for the disucssions about this change, but can't find any.
Can someone point me to those discussions? Cheers!

**Comment by klaude** [comment]
Howdy! I'm closing this issue as it duplicates #1074.

**Comment by tfiers** [comment]
Apologies! Bad internet connection at time of posting 😅 which led to double post apparently
