### ISSUE TITLE
Timeout / page inaccessible without 'www.' subdomain prefix

### ISSUE THREAD

**Issue by jayaddison** [ContributorCovenant/contributor_covenant#1425]
Hello - I've been reading some code-of-conduct-related documentation in [GitHub's `opensource.guide`](https://github.com/github/opensource.guide), and noticed that the hyperlinks from there to the Contributor Covenant tend to omit the `www.` subdomain prefix in the Contributor Covenant URLs; e.g. https://contributor-covenant.org

Those hyperlinks may have been valid in the past, but they appear broken at the moment (I encounter a timeout making web requests to that domain).  I'll propose a pull request to adjust their inbound links -- but I also thought it might be worth mentioning here first, in case it's possible to restore them, or an intermittent problem, or similar.

Thanks!
James

**Comment by klaude** [comment]
Hi Jay. Thanks for the heads up! It looks like we have DNS record or two to update. I'll hop on that and let you know when it's safe to try again.

**Comment by jayaddison** [comment]
Thank you, @klaude!

**Comment by klaude** [comment]
@jayaddison, we've fixed the DNS records. Thanks again for bringing this to our attention. I'll close this issue out.

**Comment by jayaddison** [comment]
Awesome, yep - those links are working now.  Thank you, @klaude!
