### ISSUE TITLE
Version CoC with tags

### ISSUE THREAD

**Issue by patcon** [ContributorCovenant/contributor_covenant#18]
Thanks for the project! Just thinking that managing this doc with version tags like the semver doc does (or any software project) would help users easily check whether they're up-to-date :)

https://github.com/mojombo/semver/releases

**Comment by strand** [comment]
@CoralineAda I was looking at the commit history and had difficulty discerning when our version bumps happen. If you get a moment would you go through and tag version numbers?

**Comment by xzyfer** [comment]
I just ran into this myself. GitHub release make this easy and watchers get notified of new releases which addresses #136

**Comment by CoralineAda** [comment]
Done
