### ISSUE TITLE
Provide a diff of 1.3 and 1.4

### ISSUE THREAD

**Issue by CoralineAda** [ContributorCovenant/contributor_covenant#227]

**Comment by parkr** [comment]
@CoralineAda We (Jekyll) recently updated our CoC to Contributor Covenant v1.3. Is there a diff between the two? Thanks for making this! I personally feel it's as important to FLOSS as laws are to nations.

**Comment by CoralineAda** [comment]
https://github.com/ContributorCovenant/contributor_covenant/blob/v1_4/diffs/1_3_vs_1_4.patch
