### ISSUE TITLE
Version 1.4 Polish Translation

### ISSUE THREAD

**Issue by CoralineAda** [ContributorCovenant/contributor_covenant#239]
Version 1.4 needs a Polish translation. See the diff at https://github.com/ContributorCovenant/contributor_covenant/blob/master/diffs/1_3_vs_1_4.patch. 

Attn @Kwpolska @michalsapka

**Comment by jaen** [comment]
If you don't mind me helping - I could.
I'm a bit OCD about language and when I've read 1.3 in the Polish I thought wording could be improved. Good language is a thing to strive for above any and all divisions.

**Comment by CoralineAda** [comment]
Sounds great!

**Comment by jaen** [comment]
Then I'll get back to you with a PR when I get my IRL things in order, unless someone else beats me to it (but I'll probably still chime in to nitpick the wording).

**Comment by Kwpolska** [comment]
I’ll try to get it done today. Is there a way to generate .txt and .html files?
