### ISSUE TITLE
Version 1.4 needs a Portuguese translation

### ISSUE THREAD

**Issue by CoralineAda** [ContributorCovenant/contributor_covenant#240]
Version 1.4 needs Portuguese translations. See the diff at https://github.com/ContributorCovenant/contributor_covenant/blob/master/diffs/1_3_vs_1_4.patch. 

Both Portuguese and Portugues do Brasil

Attn @benlangfeld @danifbento

**Comment by benlangfeld** [comment]
I'm working on pt_BR and should be done soon. I am, however, being slowed down by trivial things like reordering of the factors listed in "Our pledge" for which I can't fathom a motive. I'm happy to contribute with translations, as I am sure are many others, but keeping the diff free of unnecessary un-semantic changes between versions would make that task easier :)

**Comment by danifbento** [comment]
Hey, I will try to push the translation between today and tomorrow. I have been with a full agenda =)

**Comment by alexwlchan** [comment]
@benlangfeld The traits were reordered to be alphabetical, so that the order didn't inadvertently imply that some factors were more important than others. See PR #215.

**Comment by benlangfeld** [comment]
@alexwlchan Should they then be ordered alphabetically in the translated language or ordered the same as the en_US version? How can that be communicated to translators?

**Comment by danifbento** [comment]
@CoralineAda is this issue to be closed? To avoid confusion in a next iteration =)

**Comment by CoralineAda** [comment]
@danifbento Yes, thanks!
