### ISSUE TITLE
Code of conduct lacks email address

### ISSUE THREAD

**Issue by agrimm** [ContributorCovenant/contributor_covenant#256]
The code of conduct for the contributor_covenant project itself, CODE_OF_CONDUCT.md, currently lacks an email address. It merely links to http://contributor-covenant.org/version/1/4/code_of_conduct.md which has "INSERT EMAIL ADDRESS".

**Comment by CoralineAda** [comment]
Thanks for pointing this out. I'm disappointed that you tweeted about this as if it were a big deal though. Pretty uncool, Andrew.
