### ISSUE TITLE
The mantainer of this project should terminate the collaboration with the tech journal "Model View Culture" because is directed by a misandric person.

### ISSUE THREAD

**Issue by axela74** [ContributorCovenant/contributor_covenant#278]
The CEO and founder of "Model View Culture" is Shanley Kane ( [link](https://modelviewculture.com/about) ).
@CoralineAda is an author of that tech journal ( [Model View Culture Authors](https://modelviewculture.com/authors/page/3) ).

Shanley Kane published yesterday this [tweet](https://twitter.com/shanley/status/702956563430920192) 
"men disgust me
 *spits*
 trash
 trash
 trash"

Since Coraline Ada is an employee of github and is the main writer of this Code of Conduct I ask her:  Is this what the maintainer wants to be reflected in the project? Will any men developers feel comfortable contributing or adopting the CoC in their project?

Shouldn’t Coraline publicly dissociate herself from the Model View Culture magazine and from its CEO and founder Shanley Kane and terminate any collaboration with the magazine and with the CEO to prevent the risk of being associated to a person that literally wrote in a public place (twitter) that she is disgusted by an entire genre, that she express this disgust by writing "spits" and that she wrote that an entire genre is trash?

How she can work to make the github more inclusive if she at the same time works for a misandric person that writes words that offend almost 50% of all human beings?

**Comment by applesaucefever** [comment]
Yeah this sort of commentary about men is unacceptable and offensive.

**Comment by axela74** [comment]
Hi Coraline,
can you please give me a reason for closing the iusse?

**Comment by mattneel** [comment]
@axela74 Harassment or something, probably.

**Comment by CoralineAda** [comment]
Yes, it has nothing to do with Contributor Covenant? CC does not infringe on freedom of association.

**Comment by mattneel** [comment]
Unless your name is @elia, right?

**Comment by alandwarinasia** [comment]
@CoralineAda pretty funny coming from someone who uses a twitter blocklist exclusively based on guilt-by-association...

**Comment by mattneel** [comment]
@alandwarinasia Hypocrisy is cognitive dissonance + power or something.

**Comment by magicalvidyakitty** [comment]
SJWs always double-down. If you're going to try write a document creating moral authority, ensure that your moral authority is unimpeachable. Your ongoing affiliation with sexist hatemongers corrupts any moral authority you may be attempting to project.

**Comment by x1024** [comment]
The response was "Close the thread and pretend nothing happened".
Perhaps people who see tickets by Coraline Ada in their projects should follow the example and do what she does.

**Comment by mattneel** [comment]
@x1024 In all fairness, that would be the only sane response to a ticket with 0 technical merit and purely ideological underpinnings.

**Comment by x1024** [comment]
@mattneel Yes, but before it could be seen as "being rude". Now we have confirmation that this is the behavior of GitHub employees.

Presumably, they know how to behave in an open-source community, so we should use them as an example to follow.
