### ISSUE TITLE
The maintainer of this project engages in gendered slurs

### ISSUE THREAD

**Issue by CartesianDuelist** [ContributorCovenant/contributor_covenant#280]
https://twitter.com/CoralineAda/status/702662929536020481

The maintainer of this project uses two terms of endearment as an epithet describing what she believes to be unsavoury behaviour relegated to men. I feel this is no different than when people claim "I do not hate black people, just black culture", and do not feel safe with her continuing to lead the project.

**Comment by webmaven** [comment]
@CartesianDuelist, you have got to be kidding. This isn't 'male culture' she's calling out, just a particular set of behaviors, and 'dudebro' is a perfectly apt label. And your bad-faith appropriation of language used by marginalized groups is *vile*.

@CoralineAda, there is no reason to extend any benefit of the doubt here. Please go ahead and just close and lock this issue. It's ridiculous.

**Comment by CartesianDuelist** [comment]
They are labels referring to men vis-a-vis 'male culture', i.e. when someone uses a racial slur against a race but says it's only for the 'bad ones'. 

You are a disgusting human being for condoning this and should be ashamed.
