### ISSUE TITLE
How OK are you with modifications and adaptions?

### ISSUE THREAD

**Issue by BrianHicks** [ContributorCovenant/contributor_covenant#333]
Hi! Thanks for writing the contributor covenant. It's awesome, and I love it. While adapting it for our project I made the following changes: https://github.com/asteris-llc/converge/pull/330/commits/c500367cccffc46c1b2da3fbb0af9d83530804b4. The goal was to emphasize behaviors we want to see in our community. The five behaviors listed in the original text are included.

So my question: do you feel these go against the spirit of the covenant, or violate the license in any way? I'm not sure how the MIT license applies in this situation. And in any case I would rather follow the wishes of the creator and put our community guidelines elsewhere if they don't work there.

**Comment by CoralineAda** [comment]
I’m happy with additions, not subtractions. It demonstrates that you’ve actually put thought into how you want your community to take shape, which I fully support. Great job!

**Comment by BrianHicks** [comment]
Great, thanks! And thank you for the quick response!
