### ISSUE TITLE
(pt_BR) Improve "body size" translation

### ISSUE THREAD

**Issue by rmusmanno** [ContributorCovenant/contributor_covenant#366]
Hello!

In pt_BR translation: "body size" should translate to "porte físico" instead of "diferença corporal".

The first one is commonly used to refer to body build statistics such as height, weight, height/weight ratio and so on. The latter is not used in Brazil.

**Comment by CoralineAda** [comment]
Hi there! Would you mind making the change and submitting a pull request? Thanks!

**Comment by rmusmanno** [comment]
Yes I can!

It is pull request #367 

This was my first issue and pull request ever! Thank you! :D

**Comment by CoralineAda** [comment]
Oh awesome, congratulations! It's merged. ♥️
