### ISSUE TITLE
Violent maintainer should be removed from project

### ISSUE THREAD

**Issue by DelanoJ84** [ContributorCovenant/contributor_covenant#393]
Coraline Ada is publicly calling for violence against a journalist on Twitter. A website linked on her Twitter profile mentions that she is a core contributor to the Contributor Covenant. Is this what the other maintainers want to be reflected in the project? Will any pacifist developers feel comfortable contributing?

https://twitter.com/CoralineAda/status/823064825366360065

As this is also a violation of the rules in the Contributor Covenant Code of Conduct, I also request Coraline Ada be officially removed under said guidelines to help keep the project safe, specifically:

> Examples of unacceptable behavior by participants include:
> Trolling, insulting/derogatory comments, and personal or political attacks

and

>Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.

In addition, I am officially calling on Coraline Ada to retract and apologize for intimidating behavior and donate to a civil liberties charity of my choice.

**Comment by 7heo** [comment]
On her defense, what she does outside of the project should not be hold against her in regards to this project. We as individuals have a right to private lives, and what we do in our private lives does not necessarily reflect the opinion and orientation of the groups and organizations we participate in (and vice versa).

**Comment by DelanoJ84** [comment]
You raise a fair point, though it is not to be the general consensus of the Contributor Covenant community: https://github.com/opal/opal/issues/941#issue-89339611
This is also more relevant to the project than the issue Coraline opened and even tweeted about ( https://twitter.com/coralineada/status/611574385028149248 ) concerning a "transphobic maintainer" because the contributor's personal opinions on whether transsexualism have no direct bearing on Opal's stated goal of being "a Ruby to JavaScript source-to-source compiler". I'm assuming that Coraline linked to an ANTIFA member's response to the contributor in question ( https://twitter.com/krainboltgreene/status/611569515315507200 ) rather than anything the programmer actually said because this was supposed to represent what the programmer had communicated, but that would mean the worst that he could actually be accused of is that he thinks trans people are "not accepting reality", presumably about their gender. Personally, I'd feel safer working with someone who thought I was delusional than someone who thinks journalists should be assaulted for who they interview.
On the other hand, the Contributor Covenant's stated goal is:

> to be overt in our openness, welcoming all people to contribute, and pledging in return to value them as human beings and to foster an atmosphere of kindness, cooperation, and understanding.

This is incompatible with a member who apparently thinks punching people to shut them up is not only viable and funny, but that this practice should be extended to anyone who talks to them as well. It does reflect poorly on both the Contributor Covenant team and the projects which have adopted it if its own members are unwilling to enforce the thing or even acknowledge violations when it involves the clique. They might as well just add a section to list off people who are not to be bound by the CoC to the template at that point to avoid having to close similar issues as maintainers tweet their support of ANTIFA riots and lootings.

**Comment by 7heo** [comment]
I know it is not the consensus of the Contributor Covenant; and very obviously, the people behind that document do not place themselves under its rules (I have seen the so called "opalgate" before). It is common in radical groups to only apply rules to those they fight and judge, and not to themselves (open history books for further information on that subject).

However, that does not legitimate this behavior, and behaving in the same way the people behind the Contributor Covenant behave is quite clearly not the solution to the problem; as they already shown that their belief and entitlement goes much further than the extent of their reflection. Yet this humorous issue is a good thing in the sense that it allows for the present discussion to be had; and creates a precedent where they are legitimately placed in the role they ordinarily place others in, hastily, and with striking impunity. Maybe a few of them will take the time to analyze the situation and ponder whether their course of action so far (punishing mercilessly vs. educating) has been the right one.

About the except you quote, I have read the Contributor Covenant, and it is clear that the stated goal does not align with the applied usage<sup>1</sup>. This seems to indicate that the document which is now adopted by a large number of FOSS project is meant to be a political tool with a total disregard to the time-related resources of those projects much more than a unifying document acting for their development.

However, it is not our role, nor our place, to tell those projects what Code of Conduct they should adopt. We can only try to write better ones, hope than they will see the flaws of their current ones, and provide better tools to enable any project to regulate the conduct of their members readily, merely by including to their project an existing, maintained document. 

HTH.
----
Footnotes:

1. After deeper analysis, and comparison with other existing documents, which for example contain clauses limiting their effects to the communication and behavior *inside* their community; it is fair to ask whether or not the Contributor Covenant has been written as a political tool, while advertised as a one for the protection of freedom. The rise of the popularity in far-right groups has unfortunately banalized such practices in the *res publica* and it is now very common to see security and safety reasons invoked as justifications for censoring and excluding laws (deportation, silencing, minority oppression, etc.)

**Comment by Schadrach** [comment]
@7heo What she does outside the project is very much relevant, per the first sentence under Scope: "This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community."

She promotes the Contributor Covenant on her Twitter somewhat frequently.

As @DelanoJ84 pointed out above, trying to exclude what she does outside the project is the opposite of her own position during the Opal thing.

Either she accepts that she violated the very code of conduct she created and promotes to other open source projects or she is a hypocrite.

**Comment by CoralineAda** [comment]
I'm obviously a very toxic person, as evidenced by my hatred for bigots, racists, homophobes, transphobes, and other bad actors. No one should contribute to this project anymore and I should step down as sole maintainer and let it languish. I'll let the hundreds of people involved in translating the Contributor Covenant into 21 languages and the 20k open source adopters know that they are dealing with a person who believes that literal nazis should not be given a media platform so that they can find an alternate code of conduct, preferably one that leaves room for people to foment hatred under the guise of inclusivity.

Thanks for bringing this to my attention!

**Comment by 7heo** [comment]
Hatred only brings hatred.

**Comment by joelaw9** [comment]
That was about the response I'd expect from someone that violated her own CoC.

**Comment by DelanoJ84** [comment]
@CoralineAda The specific infraction is not you "believe that literal nazis should not be given a media platform" but that you condone systematic violence against journalists to bring about that goal. Almost everyone agrees that "bigotry" is wrong, that view is not incompatible with also not wanting extrajudicial assault squads against certain journalists.
It also seems odd for you to bring up how important the Contributor Covenant is to so many people is and then claim it would languish without one person's participation.

**Comment by onodera-punpun** [comment]
So it's only "toxic" if it's violence against someone you personally agree with, else it is okay? That seems very weird... Why is this not listed in the CoC?

**Comment by ivy-b** [comment]
This is somebody inciting violence. And its our community manager?

This makes me feel very unsafe.

Threats of violence and hate speech does not simply become 'ok' if you claim your opponent is a bad guy.

I am a transgender woman. Thank you for listening.

**Comment by CoralineAda** [comment]
Since this is making the rounds in various cesspools of the internet, let me make a few things clear:

- The code of conduct for this repo is Contributor Covenant 1.4, which clearly states:
>This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community. Examples of representing a project or community include using an official project e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event. Representation of a project may be further defined and clarified by project maintainers.
- My every public utterance is therefore not governed by the code of conduct for this repo unless I am officially representing Contributor Covenant.
- The tweet in question was a sarcastic response to a LITERAL NAZI GETTING PUNCHED and any attempt to twist it into "promoting violence" is facile.
- Before you go citing opalgate, [read the full story](https://medium.com/@coralineada/on-opalgate-2efd0fc1e0fd) 
- Go troll somewhere else.
