### ISSUE TITLE
Clarifying how the 'representing the project' clause works

### ISSUE THREAD

**Issue by shadowcat-mst** [ContributorCovenant/contributor_covenant#408]
While I concur that issue 393 was clearly not submitted in good faith, and even had it been that the tweet was clearly not meant seriously, I confess to being slightly confused.

In her response on issue 393, @CoralineAda says:

> My every public utterance is therefore not governed by the code of conduct for this repo unless I am officially representing Contributor Covenant.

but her twitter bio links to her patreon, which makes a point of the Contributor Covenant being her project.

However, during the opal fiasco, in https://github.com/opal/opal/issues/941#issue-89339611 she argues that elia's tweets are an issue because

> His Twitter profile mentions that he is a core contributor to opal.

and in fact I believe the 'representing the project' clause was added specifically in order to bring said tweets into scope after it was pointed out that the first version of the Contributor Covenant only covered project spaces themselves.

I'm curious as to how exactly one derives both of these conclusions - is it because his bio mentions the opal project by name, and if he merely linked to a list of his projects that included opal that would no longer be covered by the 'representing the project' clause? That seems to me like a subtle enough difference, if so, that it should probably be documented explicitly - but also a subtle enough difference that it's likely very much open to rules lawyering by assholes even if so documented. Or is there some other difference here I'm missing?

**Comment by karenetheridge** [comment]
This is a good point that I would also appreciate being clarified.  As a woman, aspects of my private life have sometimes been dragged into projects I am working on, through no act of my own, and it interferes with my ability to contribute. It would be good to have the document clearly state that anything I do in my personal life, that I do not link with my work in the project, are out of the document's scope.

**Comment by shadowcat-mst** [comment]
Having engaged with @CoralineAda on twitter about this recently, I'd note that her twitter bio now, instead, links to where.coraline.codes - but the front page of that calls out her original authorship of the contributor covenant so the same question would, so far as I can tell, still apply.

**Comment by shadowcat-mst** [comment]
Per https://twitter.com/CoralineAda/status/989597302141734912 - "I never said he was violating a CoC. I said he was making the project unwelcoming for marginalized people."

**Comment by shadowcat-mst** [comment]
So evidently the answer is "it doesn't apply to either twitter account", and I'll close the issue at this point.

**Comment by Aspie96** [comment]
This issue must absolutely be reopened.

What Coraline says is irrelevant. If the CoC is ambigous, it is. Even the FAQ don't matter. What does matter is the code itself. If we don't want the CoC to apply to personal spaces (such as a Twitter account), this must be clear and obvious, which it's not.
