### ISSUE TITLE
Add mention of wealth

### ISSUE THREAD

**Issue by her001** [ContributorCovenant/contributor_covenant#417]
Wealth should be mentioned explicitly as a quality that is accepted, harassment-free.

A different financial status should not open up someone to harassment, and the Contributor Covenant does not make any mention of this.

An example of behavior that would violate this: Teasing someone because they cannot afford hardware or software that a project integrates with. Often times this manifests in comments such as "stop being poor."

Related PR: #416

**Comment by Lynoure** [comment]
I thought the idea  is that nothing should open anyone up for _harassment_, and the list would not need to be conclusive in any way?

**Comment by her001** [comment]
I agree that the list need not be inclusive. Still, there are already many items that cover a huge amount of cases, and adding one word to the end, "wealth," covers even more. If the argument is simply that the list is too long, maybe the format should be changed or other parts of the list should be considered for removal, but I am not sure that those are the right choices.

Classism is commonly listed as one of the core prejudices in modern systematic oppression. While all of the others which are commonly included (and more) are already covered by the Contributor Covenant, class is noticeably left out. Unfortunately, social class is not easily defined, but wealth is a large part of it, and is relatively commonly discriminated against in tech. Therefore, mentioning wealth would help the code of conduct be more welcoming, by helping to address both theoretical and practical concerns.

**Comment by joshtriplett** [comment]
The current version already includes "socio-economic status", which should fully address this.

**Comment by her001** [comment]
So it does, thanks for pointing that out.
