### ISSUE TITLE
Bengali Translation

### ISSUE THREAD

**Issue by urbangeek** [ContributorCovenant/contributor_covenant#422]
Lets discuss on this. #421 
I have kept few technical terms in English to avoid confusion and keep the pledge foolproof.
Any suggestions are  welcome.

Cheers

**Comment by urbangeek** [comment]
Hi @CoralineAda , anything else I need to do?

**Comment by CoralineAda** [comment]
Sorry, this got lost in the shuffle. I'll find another Bengali speaker to review the translation!

**Comment by nilanjansiromani** [comment]
Would be happy to contribute to bengali translation

**Comment by CoralineAda** [comment]
@nilanjansiromani Thanks so much! Please review the translation that @urbangeek did and leave notes here. ♥️

**Comment by urbangeek** [comment]
Hi @nilanjansiromani , did you get a chance to review the pull request?

**Comment by nilanjansiromani** [comment]
@urbangeek I have added inline comments.
The translation looks good. Some spellings were missing appropriate unicode characters (owing to the bengali script)
Do let me know for anything else :-)

**Comment by urbangeek** [comment]
@nilanjansiromani outstanding proofreading sir. I have expressed my views in comments and made some changes in the pull request. Please review.

**Comment by urbangeek** [comment]
@nilanjansiromani , anything else needs to be changed mate?

**Comment by urbangeek** [comment]
Hi @CoralineAda , I believe this pull request is ready to ship. I made all the changes @nilanjansiromani suggested except one, which could be a typo from his part.

Let me know if any else needs to be done.

Cheers.
