### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by CoralineAda** [ContributorCovenant/contributor_covenant#425]
We would love to have the Contributor Covenant translated to Chinese. Any volunteers?

For reference: https://github.com/ContributorCovenant/contributor_covenant#translating

**Comment by tigercosmos** [comment]
Still need volunteers? I can help.

**Comment by tigercosmos** [comment]
I have opened a pull request about simplified Chinese translation. PR#434

**Comment by tigercosmos** [comment]
I think this should be closed.
