### ISSUE TITLE
URL in Project Description doesn't work

### ISSUE THREAD

**Issue by jacobherrington** [ContributorCovenant/contributor_covenant#437]
When I click the link to `www.contributor-covenant.org` my browser responds with `This site can’t be reached www.contributor-covenant.org’s server DNS address could not be found.` The browser also fails to find the site with `https://www.contributor-covenant.org`. However, It does work when `www` is excluded.

Have there been changes to the DNS configuration lately?

**Comment by CoralineAda** [comment]
Yes, I moved from GitHub pages to Netlify. I just added a CNAME for www, giving it <TTL> to update. Thanks for bringing this to my attention!
