### ISSUE TITLE
CODE_OF_CONDUCT.md link broken

### ISSUE THREAD

**Issue by ryanblock** [ContributorCovenant/contributor_covenant#459]
Looks like the link in CODE_OF_CONDUCT.md is pointing to the wrong spot (http://contributor-covenant.org/version/1/4/code_of_conduct.md), and should be pointing here: https://www.contributor-covenant.org/version/1/4/code-of-conduct/CODE_OF_CONDUCT.md

Will pop over a PR!

**Comment by CoralineAda** [comment]
Looks like these links were changed inadvertently… We’re going to be fixing the paths to change them back to what they were. Nice catch, thanks!

**Comment by ryanblock** [comment]
🙌

**Comment by CoralineAda** [comment]
Fixed in https://github.com/ContributorCovenant/contributor_covenant/pull/461
