### ISSUE TITLE
The "Latest version" link returns a 404

### ISSUE THREAD

**Issue by markvincze** [ContributorCovenant/contributor_covenant#487]
The link to the latest version (https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) on the live website returns a 404.

I'm not sure what the issue is, I tried to clone the repo and start up the site locally with `hugo`, and then it worked.

**Comment by Roshanjossey** [comment]
@markvincze, This link is working for me. Can you check again and confirm this so that we can close this issue?

**Comment by markvincze** [comment]
@Roshanjossey,
Yep, now it works for me too.
