### ISSUE TITLE
Support for asciidoc?

### ISSUE THREAD

**Issue by ivoanjo** [ContributorCovenant/contributor_covenant#488]
Hello there!

I just created a new project using the contributor covenant, but noticed that there is no asciidoc version for it.
Asciidoc is an ascii-based simple markup language, like Markdown, [that is also supported by GitHub](http://asciidoctor.org/news/2013/01/30/asciidoc-returns-to-github/).

I prefer to have all my documentation in asciidoc (instead of mixing markdown with asciidoc in the same repository), so I converted the covenant to asciidoc: <https://github.com/ivoanjo/persistent-dmnd/blob/development/CODE_OF_CONDUCT.adoc>.

Would you consider adding (or accept PRs for) support for having the covenant in asciidoc format?

Thanks, and keep up the awesome work!

**Comment by CoralineAda** [comment]
Sure thing, as long as it can be generated like the other versions with Hugo!
