### ISSUE TITLE
Clarification on publication of physical or electronic address without explicit permission

### ISSUE THREAD

**Issue by lsmith77** [ContributorCovenant/contributor_covenant#492]
In the Symfony project we are discussing adoption of the contributor covenant version 1.4 and a question was raised on if `Publishing others' private information, such as a physical or electronic address, without explicit permission` could be clarified:

```
Physical address makes a lot of sense ... but electronic address? For example, if I want to ping someone in a pull request, should I ask for permission before pinging them? (because pinging requires to expose the user electronic address on GitHub). And about the email, if that user publicly shows their email address in GitHub pull requests, should I also ask for permission to show that (already public) electronic address?
```

https://github.com/symfony/symfony/pull/24896/files#r152204663

**Comment by lsmith77** [comment]
I guess any address previously used within the public context of the project can be considered to be public .. like the email address used on the mailinglist or the github account used to submit a PR.

**Comment by lsmith77** [comment]
In turn of course even if a physical address is "public" in a phone book .. it should not be allowed to a github id used within the project with this physical address which I guess is the focus of this clause?

**Comment by CoralineAda** [comment]
That is correct. This is an anti-doxing measure.

**Comment by lsmith77** [comment]
Ok, thank you for the clarification. I am not sure if this could be clarified somehow to prevent the concerns noted in the quote I put at the top, but since I do not have a suggestion, that doesn't make things significantly longer, I am closing the ticket.

**Comment by sadeghrajabi** [comment]
لایک
