### ISSUE TITLE
enforcement team at conferences vs. community

### ISSUE THREAD

**Issue by lsmith77** [ContributorCovenant/contributor_covenant#502]
While debating the adoption of a CoC for our community (https://github.com/symfony/diversity/issues/1) and looking into creating an enforcement team (https://github.com/symfony/diversity/issues/2), I realized that there will not always be someone physically present from the enforcement team at every event covered by the CoC. As such I wonder if it makes sense to add some provision that the enforcement team should name an official delegate for every event that runs under the CoC. Do you think this is something that should get added as a provision within the enforcement section? Or do we best manage this topic outside of the CoC?

**Comment by CoralineAda** [comment]
Hi,

I think it should be clearly documented somewhere, so that attendees know about the enforcement mechanism, but where you put it is not that important.

**Comment by lsmith77** [comment]
Ok thank you for the quick feedback!

So as part of our event guidelines we will just mandate that every event contact the enforcement team in order to setup a process for reporting with people physically present and ensure that this is prominent on the website, but we will not cover this in our CoC.
