### ISSUE TITLE
Plain text is incorrectly rendered with HTML symbols

### ISSUE THREAD

**Issue by espectalll** [ContributorCovenant/contributor_covenant#521]
The code of conduct seems to be incorrectly rendered with HTML symbols, as shown at the .txt at https://www.contributor-covenant.org/version/1/4/code-of-conduct.txt:

    * Publishing others&rsquo; private information, such as a physical or electronic
    address, without explicit permission

at line 32, and

    Project maintainers who do not follow or enforce the Code of Conduct in good
    faith may face temporary or permanent repercussions as determined by other
    members of the project&rsquo;s leadership.

at line 70.

**Comment by CoralineAda** [comment]
Thanks! We'll get this fixed up soon.
