### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Sagar2366** [ContributorCovenant/contributor_covenant#522]
Can I translate this project in Marathi Language

**Comment by CoralineAda** [comment]
Sure thing! The first step is to look at https://www.contributor-covenant.org/translations.html and make sure that the translation doesn’t already exist. From there, follow the translation instructions here:

	https://github.com/ContributorCovenant/contributor_covenant#translating


After you are done, open a PR. I will then put out a call to have the translation reviewed by 1-2 other native speakers.

Thanks!

Coraline
