### ISSUE TITLE
"what is best for community" may be vague when compared to other examples

### ISSUE THREAD

**Issue by tieguy** [ContributorCovenant/contributor_covenant#555]
Doing my first read-through of 1.4, which I generally am 👍 on. The explicit examples are definitely constructive and useful.

My only quibble is the "focus on what is best for the community" example. I'm a bit unclear what behavior it is intended to encourage (or repudiate)? The other examples are pretty concrete - use this type of language, behave in this specific way, etc.; this one less so.

A rephrasing that I _think_ might improve it, but might not (since I'm not entirely clear about the original intent):

> Prioritize what is best for the community over what is best for individual contributors.

Or perhaps:

> Prioritize the health of the community.

(Still not explicit what you're prioritizing the health of the community _over_, but strikes me as more concrete than "focusing" on what is "best"?)

Both of these could be abused, as with any majoritarian language. I suspect the original language has the same problem, though.

**Comment by CoralineAda** [comment]
I like the idea of clarifying this language and will mark it for consideration in a future version. Thanks!

**Comment by tieguy** [comment]
Cool, glad the comment was helpful. 

For what it is worth, the language I ended up using in the Tidelift CoC is "Prioritizing community health over individual community members". I'm not sure that's *quite* right (anytime you de-prioritize individuals, there is some risk of getting it wrong) so I look forward to seeing what you come up with.

**Comment by tieguy** [comment]
Cool, glad the comment was helpful. 

For what it is worth, the language I ended up using in the [Tidelift CoC](https://tidelift.com/docs/code-of-conduct) is "Prioritizing community health over individual community members". I'm not sure that's *quite* right (anytime you de-prioritize individuals, there is some risk of getting it wrong) so I look forward to seeing what you come up with.
