### ISSUE TITLE
[query] Suitability beyond a software project repo?

### ISSUE THREAD

**Issue by kwill** [ContributorCovenant/contributor_covenant#561]
**User story:** I manage an online community that includes both software development (e.g. git repos) and freeform discussion (e.g. a forum). I want a single code of conduct, so that users don't have to read/review multiple codes.

---

Is adoption of the CC beyond a software project repo considered in-scope? For example:

* a wiki
* a Mastodon (or similar) instance
* a Q&A site
* an online forum
* ...basically any collaborative online space

By "in-scope" I mean that pull requests that clarify or add context for these use-cases would be accepted. This does not mean exhaustively inserting terms of art like *wiki*, *post*, *toot*, etc. In fact I don't see any immediate need for changes in any of those scenarios, but I want to know if such changes would be considered. Thanks!

**Comment by CoralineAda** [comment]
To a degree, but for online communities (like slack for example) you might want to look at http://community-covenant.net

**Comment by kwill** [comment]
I didn't know about that! On reflection, I could adopt the Community Covenant for both software repos AND other online spaces. (Participants will be able to see that the same code of conduct is used throughout.)

I think this is a better solution than confusing non-developers with some of the jargon in the Contributor Covenant. I've updated the original ticket with my actual use-case for clarity.
