### ISSUE TITLE
Should we be using gender-free language in translations ?

### ISSUE THREAD

**Issue by ewjoachim** [ContributorCovenant/contributor_covenant#573]
I was reading the [French version of the covenant (v1.4)](https://github.com/ContributorCovenant/contributor_covenant/blob/df995d0a05a08d64b276f577efec4afcef5a88e1/content/version/1/4/code-of-conduct.fr.md) and realized it was refering to maintainers as "les mainteneurs / ils", which is the masculine form.

This is grammatically and traditionnaly correct in the sense that French language tends to use the masculine form as soon as the group of people to which it applies has the slightest chance of not beeing solely composed of women, but there's actually a lot of debate over this habit, and there are lots of way to phrase this that may not be interpreted as an assumption on the maintainers gender. Given that the convenant itself states we should be "Using welcoming and inclusive language", I'm guessing this would apply :)

- We can use "Les personnes qui maintiennent / ces personnes" (The people maintaining / these persons) (or other diverted ways to avoid gendering them, like "les personnes assurant la maintenance"
- Or "Les mainteneuses et mainteneurs" (The female mainteners and male mainteners) (or the other way around, male and female)
- Or the short form "Les mainteneur·ses " (same with one of the non-official ways to shorten the writing. That's the one I find to be most readable, but there's still a lot of debate)
- We could also be alterning between the 2 forms in the text, but that's probably making it harder to read and understand.
- Or we can do nothing and rely on people's ability to mentally see mainteners designated as male to be actually either male or female. (it will be grammatically wrong if there are only women maintaining the project)
- Or most probably there are other alternatives. I'd be interested to know how other languages have tackled this problem.

If we were talking about wizards here, I have no doubts, we'd not forget to say "and witches" :D

I'll be delighted to make a PR if we reach a consensus.

Ping @benoittgt who was, if my git blame skills serve, the main contributor on the current French version, and @camilleroux who was the latest.

**Comment by CoralineAda** [comment]
This is a great observation. I'll wait to hear from the pingees.

**Comment by camilleroux** [comment]
Inclusive language is a very good idea and, I think, match the goal of this Code of Conduct.
The first solution (using [épicènes](https://en.wiktionary.org/wiki/épicène) words) is probably the best (not going to create debate) but doesn't work for everywhere. The 2 followings solutions are more and more used. OK with them too (I'm using them all the time).
I'm ok to help if needed :)

**Comment by DamienR** [comment]
My god, you people are insane time wasters. Who dreamed this crap up?
