### ISSUE TITLE
The covenant appears to help the owners more than it does the harassed

### ISSUE THREAD

**Issue by wireddown** [ContributorCovenant/contributor_covenant#583]
_List of disclaimers: I'm not a lawyer; I don't know the requirements and constraints for such an internationally used document; and I'm pretty sure what I'm suggesting is negligible compared to the many other priorities for this important work._

But... I can see how one piece in the **Enforcement** section could be poorly received by a minority or marginalized member and discourage them from participating in a community or reporting a problem:

> All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances.

That distant disinterested phrasing, "deemed necessary," carries a reluctant and case-by-case tone. I'm sure others have experienced it as a patronizing or status-quo dismissal. I'd like to see stronger wording that places more responsibility and accountability on the project team -- one way to bring equity is to give more power to the oppressed and harrassed.

But: no other people have mentioned this from what I can tell (my [search](https://github.com/ContributorCovenant/contributor_covenant/issues?utf8=%E2%9C%93&q=is%3Aissue+deem)), and that matches my disclaimer above 😃

**Comment by CoralineAda** [comment]
Enforcement is (deliberately) left in the hands of project maintainers, and will look different for every project. The main CC site makes this clear in the Enforcement section. Thanks for raising this though!
