### ISSUE TITLE
What happened to #584?

### ISSUE THREAD

**Issue by skylarmt** [ContributorCovenant/contributor_covenant#586]
It just vanished, while other PRs were simply closed due to a renaming of the master branch.

**Comment by falkTX** [comment]
I had no idea github could do this... what was the issue in there?
Must have been quite serious if they can just remove it completely...

**Comment by skylarmt** [comment]
I wasn't able to find a mirror (I really did try), but it was titled "why are you even using the term sex?".  I know that because I got a notification email when it was closed.  I clicked the link in the notification within half an hour of the email being sent, and it was the standard GitHub 404 page.

https://github.com/ContributorCovenant/contributor_covenant/pull/584

It was too new to be indexed, so it wasn't even in Google's cache.  I searched the exact URL as well as the title phrase in quotes.  I also checked multiple archive websites just in case.

**Comment by skylarmt** [comment]
OK, here's a screenshot of my GitHub notifications.  It's still in there, so I can see who the participants are.  @Sooja is the creator of the PR, but his account (https://github.com/Sooja) also 404s.  So I guess when someone nukes their GitHub account it removes all their PRs.

![screenshot_2018-09-25 build software better together](https://user-images.githubusercontent.com/6668965/46035560-8c9aa900-c0c0-11e8-9408-8d9cd16db426.png)

**Comment by falkTX** [comment]
hmm interesting.
looking around I saw https://github.com/isaacs/github/issues/579 which is the same situation.
github does not support private issues yet, so the creator of #584 either deleted their own account or got banned.
this is quite troubling, tbh.
now I fear if someone is going to do the same for my account... shit...

**Comment by skylarmt** [comment]
I'll add this to the list of reasons I self-host all my projects with Gitea.  I control the server and if something like this is deleted I can still find it, even if it means spinning up one of the backups as a separate VM and accessing an old version of the site.

**Comment by falkTX** [comment]
@CoralineAda please provide an explanation here, please...
If reporting an account gets it banned, I do need to know.
What happened here?
