### ISSUE TITLE
Making the Covenant democratic

### ISSUE THREAD

**Issue by debackerl** [ContributorCovenant/contributor_covenant#587]
Hello,

I find little information about the democratic process of electing the board of reviewers. It looks like anyone can submit but only one person is allowed to accept pull requests. This may be fine, but only if that person was democratically elected. It would even be better if it was a group of people, given the ease that technology can offer us to organize this.

This is important because rules in this covenant have a deep impact on the way people are asked to behave, communicate, and even asks for sanctions against infractors. Basically, it does a job similar to the European Commission.

I can't really think of any country based on the rules of one individual which turned good in the long turn.

Note that I have no problem with software projects controlled by one individual. This is similar to a shop controlled by one owner, but regulated by its government. Given the long list of projects adhering to the Covenant, soon it will be difficult to contribute to any FOSS without being impacted by the Covenant. 

Kind regards,

Laurent

**Comment by CoralineAda** [comment]
Open source projects are not democracies.

**Comment by beoran** [comment]
I fully agree with this point. Open source projects are not democracies. Open source projects, like any other projects, rightfully belong to the ones who have worked on them. 

That is exactly why outsiders cannot barge in and demand that maintainers be removed from the fruit of their labour for any perceived or real slight, not even for real crimes. For instance, look at how Reiserfs still is part of the Linux kernel. 

Only if the other maintainers agree, for whatever reason, that they do not want to cooperate with one or more amongst themselves, the only three ethical things they can do is either a hostile fork where both sides are allowed to use each other's work, or a full rewrite of the contributions of the ones to be banned, or a financial or similar compensation for the work.

This is also, why, as it stands now, the CoC is problematic for open source projects. In the past it has been used as a tool by outsiders to barge into a project, use the social media to pillory maintainers and then demand that one or more of them should be denied their rightful property. Only with fundamental modifications to this CoC, such abuse could be made impossible, to ensure that the rightful owners of open source projects remain as such.

**Comment by ghost** [comment]
@beoran See #580 for a proposed solution.
Sadly it was closed without much discussion.

**Comment by beoran** [comment]
I know, and it is the full right of the maintainers of this project to do so. However, I would like them to take more interest in the rights of the workers, rights which they rightfully claim for themselves, rights which they must logically and ethically also grant to the full to all other maintainers of all open source projects.
