### ISSUE TITLE
The name "CoC" sounds like "cock" which is sexist

### ISSUE THREAD

**Issue by SharpOB** [ContributorCovenant/contributor_covenant#588]
How dare you.

**Comment by falkTX** [comment]
This is the most pointless thing to complain about.
Whatever you rename it to, there is very likely something in a language that is similar to a swear or bad word.

afaik no one reads out loud "CoC" in the way you describe.
Being an acronym we read it as "c-o-c" (with spaces in between).

**Comment by ShadowGoat** [comment]
I am also very offended by this

**Comment by falkTX** [comment]
of course you are, github user for a day...
you are not helping at all, just trying to find something to be noisy about.
