### ISSUE TITLE
clarification of published email address as being not private information

### ISSUE THREAD

**Issue by tbird20d** [ContributorCovenant/contributor_covenant#590]
Hello - I'm a member of the Linux kernel community and a number of questions have been raised there about the new Code of Conduct, which is based on contributor convenant 1.4.  I'm new here.  I apologize if this is not the correct venue, but is there a mail list or other site where discussion takes place, or is this it?

In any event, one issue that has caused concern is this statement: "* Publishing others’ private information, such as a physical or electronic address, without explicit permission" as an example of unacceptable behavior.  As part of the Linux development process, contributors post their e-mail addresses to public lists, and include their e-mail addresses in commit messages (in signed-off-by lines, or other meta-data lines in the commit messages).  The concern is that this treatment of e-mail addresses violates this example.  Some developers have tried to assure contributors that once an e-mail address is voluntarily published by using on a public list or in a publicly available git commit message, it automatically becomes not private information.

My question is has anyone else brought this up?  Is there some way to clarify this to ameliorate concerns with the Linux community about this issue.  Do you think that clarification is best done in a sideband document, or as a change or addition to the covenant language?

I'm happy to work on such language myself, but it seems like it would be good to discuss this to get consensus on appropriate language to propose for a pull request (if that's the recommended approach).

Thanks and regards,
 -- Tim Bird

**Comment by CoralineAda** [comment]
In the case of a mailing list, the person’s email address is public and not private, so I don’t think this would be an issue. Attaching your email to a mailing list post is an implicit permission to use it, right?

I’m happy to consider alternative language if you think that would be helpful.

**Comment by tbird20d** [comment]
I agree that it shouldn't be an issue.  Two suggestions that have come up in the community are to 1) address it with a FAQ, and 2) to add the following to Linux' CoC:
----
 * Publishing others’ private information, such as a physical or electronic address[1], without explicit permission

[1] Note that e-mail addresses used on public mailing lists are not
considered to be private information and can (in fact should) be used
to give credit in Reported-by, Acked-by, Tested-by etc. tags.
----
I think the latter is awkward as a change to the covenant text, but the note would be OK in an FAQ. 
As you say, posting an e-mail is implicit permission to use it, but the example says there should be explicit permission.  So another idea would be to just remove the word "explicit" and just say "without permission".  However, would that weaken the example and open the door to wrong interpretations of permission?

What do you think?

**Comment by tbird20d** [comment]
Sorry - I don't now what went wrong with the markup.  My bad.

**Comment by CoralineAda** [comment]
I think either of those approaches would be good.

**Comment by tbird20d** [comment]
OK - I think I would prefer to leave the wording about explicit consent being required for revealing private information in the covenant, and add a comment in a FAQ clarifying that public information is not considered private.  I see that CristinaMendoca has suggested adding a FAQ to the project (issue #575), and I added a comment there on this topic.

If Cristina or someone else does not carry through with creating the FAQ, I will try to circle back and work on that.

**Comment by CoralineAda** [comment]
Thanks!

**Comment by CoralineAda** [comment]
@tbird20d Would you mind leaving a comment on the FAQ issue?
