### ISSUE TITLE
[PATCH] code-of-conduct: Remove explicit list of discrimination factors

### ISSUE THREAD

**Issue by geertu** [ContributorCovenant/contributor_covenant#610]
Providing an explicit list of discrimination factors may give the false impression that discrimination based on other unlisted factors would be allowed.

The attached patch (originally submitted for Linux, but people told me it should be submitted here instead, as it is not Linux-specific) fixes that.
I believe it also fixes https://github.com/ContributorCovenant/contributor_covenant/issues/476

Alternatively, the list could be marked containing examples, cfr. the other examples in the document, but that would not fix #476.

[0001-code-of-conduct-Remove-explicit-list-of-discriminati.txt](https://github.com/ContributorCovenant/contributor_covenant/files/2455319/0001-code-of-conduct-Remove-explicit-list-of-discriminati.txt)

Thanks for considering!

**Comment by CoralineAda** [comment]
I'm not going to make this change to the Contributor Covenant itself, since I believe that explicitly listing examples of protected classes is important. However, any adopting project is free to modify the document according to the license.

**Comment by joshtriplett** [comment]
I suspect that the concern here might be better addressed by a FAQ entry, along these lines:

-----

**The Contributor Covenant explicitly lists a set of protected classes; does this make it acceptable to discriminate or make others feel unwelcome based on other factors?**

No. The Contributor Covenant explicitly lists protected classes for many reasons, such as reminding people to give them appropriate consideration, and assuring people in those protected classes that they are welcome. However, this is not an invitation for rules lawyers to seek loopholes, or to discriminate against others or make people feel unwelcome based on criteria not listed here. (With the notable caveat that [those who discriminate or make others feel unwelcome are themselves not welcome](https://en.wikipedia.org/wiki/Paradox_of_tolerance).)

-----

Does something along those lines sound plausible?

**Comment by CoralineAda** [comment]
I like this idea. Mind opening a PR?

**Comment by joshtriplett** [comment]
@CoralineAda Will do.

**Comment by joshtriplett** [comment]
Done: https://github.com/ContributorCovenant/contributor_covenant/pull/612

**Comment by x1024** [comment]
All classes of people are equal, but some of them are more equal than others.
