### ISSUE TITLE
Page Not found

### ISSUE THREAD

**Issue by MubashirullahD** [ContributorCovenant/contributor_covenant#633]
Hey there. 
I am doing the community-starter-kit course from lab.github.com and the last part of the course was adding the code of conduct file. I was referenced to this website [https://www.contributor-covenant.org/](url) and asked to copy the markdown. Well, the link [https://www.contributor-covenant.org/version/1/4/code-of-conduct.markdown](url) is broken and I get this text displayed:

![image](https://user-images.githubusercontent.com/45071858/49452506-21c5c680-f803-11e8-8d52-f3c07a134910.png)

Thanks in advance.

**Comment by CoralineAda** [comment]
Thanks for finding this… we’re working on a fix now and should resolve this later today.

**Comment by CoralineAda** [comment]
This is fixed!
