### ISSUE TITLE
Ambiguous Sentence in Scope-section

### ISSUE THREAD

**Issue by june128** [ContributorCovenant/contributor_covenant#659]
I'm currently adding a modified version of the Contributor Covenant to a project that I'm contributing to/maintaining. In a discussion about the Code of Conduct we found the following sentence (in the Scope-section) to be quite ambiguous:

```
This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community.
```

The meaning of this sentence isn't really clear, since the `when an individual is representing the project or its community`-part could either apply to the whole sentence or only to the second half (`in public spaces`).

If I understood it correctly, the `when [...]`-part only applies to the second half.
We therefore came up with the following modification to make the sentence unambiguous:

```
This Code of Conduct applies within all project spaces; it also applies in public spaces when an individual is representing the project or its community.
```

Please let me know what you think. I'm also happily creating a PR, if this is a wanted change.

**Comment by CoralineAda** [comment]
It could maybe be "This Code of Conduct applies within all project spaces, and also applies when an individual is representing the project or its community in public spaces."

**Comment by june128** [comment]
Yeah, I think that also makes it unambiguous enough. The use of a semicolon was a point in the discussion we couldn't agree on, so that comes down to personal taste I guess.

**Comment by june128** [comment]
I just realized that you also put the `in public spaces` at the very end of the sentence and I think that removes all ambiguity well.
I created a PR with the change: https://github.com/ContributorCovenant/contributor_covenant/pull/660

**Comment by june128** [comment]
#660 resolved this issue.
