### ISSUE TITLE
Tense confusion in opening sentence

### ISSUE THREAD

**Issue by alisonatwork** [ContributorCovenant/contributor_covenant#695]
We are in the process of adopting a modified version of the Contributor Covenant in several open source projects that we maintain. One minor change we are making is detailed in #644 but another one is to remove tense confusion that arose between 1.3 and 1.4.

In 1.3:

> we pledge to respect all people [and] we are committed to making participation

In 1.4:

> we [...] pledge to making participation

There was some discussion around how this sentence in 1.4 should say "pledge to make" instead of "pledge to making". Searching both phrases online seems to show a preference for the former.

How do you feel about making this clarification upstream? I would be happy to open a PR.

**Comment by CoralineAda** [comment]
Yes, feel free, and thanks!

**Comment by alisonatwork** [comment]
Thanks for the quick merge! #696 has resolved this issue.
