### ISSUE TITLE
Draft 2.0 discussion

### ISSUE THREAD

**Issue by CoralineAda** [ContributorCovenant/contributor_covenant#710]
Please use this thread to discuss the draft of Contributor Covenant 2.0
(https://github.com/ContributorCovenant/contributor_covenant/pull/709)

**Comment by gr2m** [comment]
Thanks Coraline for your hard work! I appreciate you list the differences between the two versions. I wonder if there is a way to see a git diff (if that\ would be useful at all)?

**Comment by nmstreethran** [comment]
Hi Coraline, the [link to the latest version of the CoC provided in the attribution section](https://www.contributor-covenant.org/version/2/0/code_of_conduct#attribution) is broken. It's caused by the use of underscores instead of dashes in the markdown file name. I'm unsure if it's more appropriate to correct the link, or to change the file name, so I thought I should point it out to you. Thanks!

**Comment by CoralineAda** [comment]
Oh, thanks for finding this! I didn’t realize that I changed from code-of-conduct to code_of_conduct in 2.0. 

Fixed!

**Comment by paulolimac** [comment]
Is v2.0 released?
if yes, please when possible, update:

- ~~[_Latest version_ menu link](https://www.contributor-covenant.org/version/2/0/code_of_conduct)~~ already updated;
- [_Latest version_ homepage section](https://www.contributor-covenant.org/#contributor-covenant-v1-4-1);
- [_Badge_ from shield.io](https://www.contributor-covenant.org/#using-the-contributor-covenant);
- [_Translations_ links](https://www.contributor-covenant.org/translations);

**Comment by CoralineAda** [comment]
Great call. I updated the badge, but the translations will update with each 2.0 translation.

Thanks!

**Comment by paulolimac** [comment]
nice @CoralineAda 

about the badge, you updated 1 of 2.
The _code snipet is outdated_:

`[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-v1.4%20adopted-ff69b4.svg)](code-of-conduct.md) `
[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-v1.4%20adopted-ff69b4.svg)](code-of-conduct.md) 

update it to:

`[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-v2.0%20adopted-ff69b4.svg)](code-of-conduct.md) `
[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-v2.0%20adopted-ff69b4.svg)](code-of-conduct.md)

**Comment by CoralineAda** [comment]
Oops, fixed!
