### ISSUE TITLE
CoC Should Protect Radical Feminists and Gender Critical Men and Women

### ISSUE THREAD

**Issue by ChristinaAD** [ContributorCovenant/contributor_covenant#713]
As a radical feminist, I believe women are oppressed on the basis of their biology, and that gender is a social construct. Accordingly, I cannot, in good conscience, pretend as if it were possible for a man to be a woman.

The Contributor Covenant does not, in its current state, seem to protect my right to hold these beliefs. Please add a clause explicitly stating that women shall not be compelled to use speech that denies their own biological reality, and that they shall not be retaliated against for declining to use preferred pronouns.

Without such a clause, the Contributor Covenant is in effect a barrier to participation by women, particularly those who choose not to be spoken for by men, however those men may identify.

As a professional software developer and a woman who has been contributing to Free and Open Source Software for over 15 years, I have never felt so unwelcome.

Please address.

**Comment by falkTX** [comment]
hmm what happened here?
