### ISSUE TITLE
Update changelog for 2.0

### ISSUE THREAD

**Issue by josegonzalez** [ContributorCovenant/contributor_covenant#744]
I was going through an org I manage and saw that I didn't have an org-wide code of conduct, so wanted to check if CC had an update. Noticed that the 2.0 version came out - cool! - but the changelog wasn't updated - womp womp.

Would be awesome if someone more knowledgeable about the update could get that updated (I'm reading through it now myself, might get a chance to make the PR).

Thanks in advance!

**Comment by Jorgeptz** [comment]
`.`

**Comment by Eomm** [comment]
I agree

Translating the ita version, I think the breaking changes are:

- there is no more reference to a "project", but only to a "community"
- now the responsibles are the community leaders and no more the project maintainers
- enforcement guidelines to standardize how to act when there is a case

Of course, there are other changes to be more inclusive (like `visible or invisible disability`) but that would be a semver-minor and not a semver-major in my opinion.

**Comment by oleg-nenashev** [comment]
@CoralineAda are there plans to add a changelog and a Git tag for Contributor Covenant 2.0? We are working on updating the Contributor Covenant version in the Jenkins project ([dev list thread](https://groups.google.com/forum/#!topic/jenkinsci-dev/u0T56f9MSZY)), and it is hard to evaluate the changes between versions. The list from @Eomm helps a lot, but it would be great to have an official comparison of v2.0 vs. v1.4.

Related discussions/issues with some info:

* https://github.com/ContributorCovenant/contributor_covenant/pull/709
* https://github.com/ContributorCovenant/contributor_covenant/issues/710

Thanks!

**Comment by CoralineAda** [comment]
Hi Oleg,

Let me take a crack at this over the weekend. Is there some reason that you want to consider 1.4 over 2.0?

**Comment by oleg-nenashev** [comment]
Hi @CoralineAda, thanks for a quick response! 

> Is there some reason that you want to consider 1.4 over 2.0?

Personally I prefer 2.0. It is more specific w.r.t responsibilities, and it is important when it comes to large communities with dozens/hundreds of maintainers. I suggested 1.4 in our community as a target, because this is the version being used by our foundation.

It does not immediately prevent us from using Contributor Covenant 2.0, but it needs a review by the foundation members to ensure that stay aligned with it and other projects. And this is where a public changelog for 2.0 would be really helpful.

**Comment by oleg-nenashev** [comment]
I made an attempt to create a changelog in https://github.com/ContributorCovenant/contributor_covenant/pull/800 . Hopefully it helps as a foundation for the final changelog.

**Comment by josegonzalez** [comment]
Yeah that seems to work, thank you @oleg-nenashev for following up here, it is definitely appreciated, and thanks to everyone else for bumping this too!

**Comment by oleg-nenashev** [comment]
Happy to help!
