### ISSUE TITLE
Does 2.0 effectively replace the Community Covenant?

### ISSUE THREAD

**Issue by lofidevops** [ContributorCovenant/contributor_covenant#756]
The ["Contributor Covenant 2.0 Draft"](https://opencollective.com/contributor-covenant/updates/contributor-covenant-2-0-draft) and related [PR](https://github.com/ContributorCovenant/contributor_covenant/pull/709) suggest that Contributor 2.0 effectively supersedes [Community 1.0](https://community-covenant.net). Is that right?

Obviously anyone can adopt whatever version of whatever code. I'm asking from a project perspective whether your intention is to focus on further updates to the Contributor Covenant and not really pursue the Community Covenant any/much further.

**Comment by CoralineAda** [comment]
That is accurate, yes. The Contributor Covenant should now be applicable in the situations that the Community Covenant was designed for.
