### ISSUE TITLE
404 CoC v2.0

### ISSUE THREAD

**Issue by Eomm** [ContributorCovenant/contributor_covenant#783]
In docs there is this link:
https://www.contributor-covenant.org/version/2/0/code-of-conduct.html

that brings me to a 404 page:

![image](https://user-images.githubusercontent.com/11404065/83351187-1b55d380-a342-11ea-85aa-9150a3ae3cdc.png)

Should it be https://www.contributor-covenant.org/version/2/0/code_of_conduct/ ?

**Comment by avats-dev** [comment]
#### Hey @Eomm , I think you're right. 
Should I correct it?

**Comment by Eomm** [comment]
I think it could be improved.

Right now if you navigate to:
- https://www.contributor-covenant.org/version/2/0/code_of_conduct/
- then click in the bottom link: 

![image](https://user-images.githubusercontent.com/11404065/89266863-badf5d00-d636-11ea-887d-1305116bc885.png)

It works since netlify return a 301 that does the right redirect.

Instead, if I just start from a CoC like this one:
- https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md

then from the bottom

```
## Attribution

This Code of Conduct is adapted from the [Contributor Covenant][homepage],
version 2.0, available at
https://www.contributor-covenant.org/version/2/0/code_of_conduct.html.
```

I just copy-paste the link, it returns 404

Maybe it is a matter of configuration of the server?

**Comment by Eomm** [comment]
It is fixed now
