### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by xmunoz** [ContributorCovenant/contributor_covenant#825]
There is a link in the README that shows search results for projects that have adopted the Contributor Covenant.

> This code of conduct has been adopted by [more than 35,000 open source projects](https://github.com/search?q=%22This+Code+of+Conduct+is+adapted+from+the+%5BContributor+Covenant%5D%22+fork%3Afalse&type=Code).

The first search result is someone who has managed to trick this filter, and adopt something that is distinctly not in the spirit of the Contributor Covenant.

![Screenshot from 2020-09-04 10-24-52](https://user-images.githubusercontent.com/1065196/92269392-f15c0200-ee98-11ea-80db-d0301244c6b0.png)

It's [this repository](https://github.com/ecdsa521/transmission-process/blob/master/CodeOfConduct.md).

**Comment by james-sabel** [comment]
Yikes! Do you think there's a way to create a different filter? Or maybe some sort of "white list" for those who *really* adopted the Contributor Covenant?

**Comment by MikeRogers0** [comment]
I figured out how the gamed it: They searched for the term, then clicked their own repo a bunch of times. I'm guessing GitHub is tracking clicks & feeding that into search results.
So if you click on your preferred results, they'll start to outrank that person. You can see it working if you start clicking results, then refresh the page.

One possible solution is to change the link to be [`https://github.com/search?o=desc&q=%22This+Code+of+Conduct+is+adapted+from+the+%5BContributor+Covenant%5D%22+fork%3Afalse&s=indexed&type=Code`](https://github.com/search?o=desc&q=%22This+Code+of+Conduct+is+adapted+from+the+%5BContributor+Covenant%5D%22+fork%3Afalse&s=indexed&type=Code) it's still open to being abused, but there could also be enough throughput to not give negative people to much publicity.

**Comment by xmunoz** [comment]
I tried to flag the abuse to Github, but they effectively shrugged it off.

**Comment by CoralineAda** [comment]
Thanks for trying. 🖤
