### ISSUE TITLE
Better Diffs

### ISSUE THREAD

**Issue by EndangeredMassa** [ContributorCovenant/contributor_covenant#87]
I love that the website has direct URLs for different versions, but the source code being structured this way makes it difficult to see actual diffs. Reviewing things like https://github.com/CoralineAda/contributor_covenant/pull/83 is therefore much more difficult.

I assume it is set up this way because the project uses Github Pages, making this easy to deploy. Is there a way to maintain that value but also allow PRs to show more direct diffs?

The alternative seems to be to deploy different versions of the site to different URLs on a real server, adding to the work required to maintain this project. If that's the trade-off, the current situation is probably better.

Side note: For markdown specifically, I like to structure it so that each phrase has its own line. It renders the same, but diffs can be much clearer.

**Comment by CoralineAda** [comment]
I've created diff files now, available in the 'diffs' folder.
