### ISSUE TITLE
Broken link in German 2.0 version

### ISSUE THREAD

**Issue by fkohrt** [ContributorCovenant/contributor_covenant#901]
The German 2.0 version currently links to

`https://www.contributor-covenant.org/de/version/2/0/code-of-conduct`

but correct is

`https://www.contributor-covenant.org/de/version/2/0/code_of_conduct/`

**Comment by Dramaqueen76** [comment]
> The German 2.0 version currently links to
> 
> `https://www.contributor-covenant.org/de/version/2/0/code-of-conduct`
> 
> but correct is
> 
> `https://www.contributor-covenant.org/de/version/2/0/code_of_conduct/`
