### ISSUE TITLE
Versioning/clarification after adding "caste, color"

### ISSUE THREAD

**Issue by SebastianWolf-SAP** [ContributorCovenant/contributor_covenant#965]
A community member of one of our projects [informed us about the missing words 'caste, color'](https://github.com/corona-warn-app/cwa-app-ios/pull/3016) in our code of conduct which is derived from the Contributor Covenant 2.0. I did [a small investigation](https://github.com/corona-warn-app/cwa-app-ios/pull/3016#issuecomment-869679619) and it came out that these two words were added in February/March while the version of the Contributor Covenant remained on 2.0.

As the [code of conduct for the Contributor Covenant](https://github.com/EthicalSource/contributor_covenant/blob/release/CODE_OF_CONDUCT.md) itself is also lacking these two words and the most recent version is still 2.0 which doesn't contain these words, I would appreciate a clarification regarding this change, especially if that change was intentional or not (see also the discussion in https://github.com/EthicalSource/contributor_covenant/issues/787). If it was intentional, I'd ask @CoralineAda or anybody else who is entitled to do that to reflect this change in a new version (maybe 2.0.1) so that all consumers can adopt it properly.

Thanks in advance!

**Comment by CoralineAda** [comment]
Hey Sebastian, I'm taking a break this week but will be back to work through this soon. Thanks!

**Comment by Ein-Tim** [comment]
@CoralineAda 

Hi, did you have time to look into this yet? 

Thanks for the update!

**Comment by CoralineAda** [comment]
https://github.com/EthicalSource/contributor_covenant/pull/976

/cc @Ein-Tim @SebastianWolf-SAP

**Comment by SebastianWolf-SAP** [comment]
Good to have the version question now addressed. I still have some questions regarding the changes for v2.1, see my comments to the PR. The thing is that we simply need to see if the changes are that important to justify a roll-out of a new version to our projects or if v2.0 might be fine for now...
